#!/bin/bash
#
# this script parses lognames to the log_save script
#
# By shalira 27.07.01
#

savelog=`/prod/logs/log_save`

cd /prod/logs


#
# Enter the logs to be saved for more than a week here
# You have to enter the full path to the log, so the
# format is: $savelog /prod/logs/<logname>
#
#

log_save wrongpw
