#!/bin/bash
#
# script to automaticly save the last weeks logfile
#
# it is called by log_save <log name>
#
# Do not change unless you know what you are doing
#
# By Shalira 27.07.01
#

year=`date "+%y"`
month=`date "+%m"`
day=`date "+%d"`

suffix="$day$month$year"

cat $1.7 $1.6 $1.5 $1.4 $1.3 $1.2 $1.1 >old_logs/$1.$suffix
